version: '3'
volumes:
    postgres-data: {}

services:

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: on-failure
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: cloudv2
    networks:
      - demo
    volumes:
      - postgres-data:/var/lib/postgres   

  python_app:
    build: .
    command: bash -c "cd cloud_computing_project &&  python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres_db
    environment: 
      DB_PASSWORD: "postgres"
      DB_NAME: "cloudv2"
      DB_USERNAME: "postgres"
      DB_PORT: "5432"
      DB_HOST: "postgres_db"
      SECRET_KEY: django-insecure-t4z^t7sh)4=5j6esg0(*ldqw3kcxpb+l^&ivqs*=6xc)b7!h%7
    networks:
      - demo
    ports:
      - 8000:8000
    restart: on-failure

networks:
  demo:
    driver: bridge